src/Entity/CartePostale.php
<?php

namespace App\Entity;

use App\Repository\CartePostaleRepository;
use App\Trait\TimeStampTrait;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CartePostaleRepository::class)]
#[ORM\HasLifecycleCallbacks]
class CartePostale
{   use TimeStampTrait;
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $imagefront = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $imageback = null;

    #[ORM\Column]
    private ?float $prix = null;

    #[ORM\Column(type: Types::SMALLINT, nullable: true)]
    private ?int $quantite_stock = null;

    #[ORM\ManyToOne(inversedBy: 'cartePostales')]
    private ?Region $region = null;
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getImagefront(): ?string
    {
        return $this->imagefront;
    }

    public function setImagefront(?string $imagefront): static
    {
        $this->imagefront = $imagefront;

        return $this;
    }

    public function getImageback(): ?string
    {
        return $this->imageback;
    }

    public function setImageback(?string $imageback): static
    {
        $this->imageback = $imageback;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function getQuantiteStock(): ?int
    {
        return $this->quantite_stock;
    }

    public function setQuantiteStock(?int $quantite_stock): static
    {
        $this->quantite_stock = $quantite_stock;

        return $this;
    }

    public function getRegion(): ?Region
    {
        return $this->region;
    }

    public function setRegion(?Region $region): static
    {
        $this->region = $region;

        return $this;
    }
    public function getPays(): ?string
    {
        return $this->region ?->getPays()?->getName();
    }
    public function getPaysId(): ?int
    {
        return $this->region ?->getPays()?->getId();
    }
}

templates/Cartes/add.html.twig
{% extends 'template.html.twig' %}

{% block body %}
    {{ form_start(form) }}
    <div class="row">
        <div class="col-6">
            {{ form_row(form.name) }}
        </div>
        <div class="col-6">
            {{ form_row(form.prix) }}
        </div>
        <div class="col-6">
            {{ form_row(form.region) }}
        </div>
        <div class="col-6">
            <a href="{{ path('cards.addRegion') }}" class="btn btn-outline-secondary">Région manquante?</a>
        </div>
    </div>
        {{ form_rest(form) }}



{% endblock %}

{% block title %}

{% endblock %}

templates/Cartes/addRegion.html.twig
{% extends 'template.html.twig' %}

{% block title %}
Ajout de région
{% endblock %}

{% block body %}
{{ form(form) }}
{% endblock %}

templates/Cartes/detail.html.twig
{% extends 'template.html.twig' %}

{% block title %}{{ carte.name }} | Détail de la carte{% endblock %}

{% block PageTitle %}
    Détail de la carte
{% endblock %}

{% block body %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <!-- Left: Original Card -->
        <div class="col-md-4">
            <div class="card" style="width: 100%;">
                <div class="card-body">
                    <h5 class="card-title">{{ carte.name }}</h5>
                    <div class="row">
                        <div class="col-sm">
                    <img src="{{ asset('/assets/cartes_postales/' ~ carte.imagefront) }}" alt="{{ carte.name }}" class="img-fluid mb-3">
                        </div>
                        <div class="col-sm">
                    <img src="{{ asset('/assets/cartes_postales/') ~ carte.imageback | defaultImage }}" alt="{{ carte.name }}" class="img-fluid mb-3">
                        </div>
                    </div>
                    <p class="card-text">Prix: {{ carte.prix }} DT</p>
                    <h6 class="card-subtitle mb-2 text-body-secondary">
                        Stock: {{ carte.quantiteStock }}
                    </h6>
                </div>
            </div>
        </div>

        <!-- Right: Details & Add to Cart -->
        <div class="col-md-8">
            <div class="card shadow-sm">
                <div class="card-body">
                    {# <h3 class="card-title">Détails du produit</h3> #}
                    <p class="card-text">Nom: <strong>{{ carte.name }}</strong></p>
                    <p class="card-text">Prix unitaire: <strong>{{ carte.prix }} DT</strong></p>
                    <p class="card-text">Stock disponible:
                        {% if carte.quantiteStock > 0 %}
                            <span class="text-success">{{ carte.quantiteStock }}</span>
                        {% else %}
                            <span class="text-danger">Rupture de stock</span>
                        {% endif %}
                    </p>

                    {% if carte.quantiteStock > 0 %}
                        <form action="{{ path('ajouter_au_panier', {id: carte.id}) }}" method="post">
                            <div class="mb-3">
                                <label for="quantity" class="form-label">Quantité</label>
                                <input type="number" name="quantity" id="quantity" class="form-control" value="1" min="1" max="{{ carte.quantiteStock }}">
                            </div>
                            <button type="submit" class="btn btn-primary w-100">Ajouter au panier</button>
                        </form>
                        <p></p>
                        <p class="card-text">
                            En Panier:
                            <strong>
                                {{ session.get('panier')[carte.id] is defined ? session.get('panier')[carte.id] : 0 }}
                            </strong>
                        </p>
                    {% else %}
                        <button class="btn btn-secondary w-100" disabled>Indisponible</button>
                    {% endif %}
                    {% if session.get('panier')[carte.id] is defined and  session.get('panier')[carte.id] != 0 %}
                        <a href="{{ path('panier.voir') }}" class="btn btn-success w-100 mt-2">Acheter Maintenant</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/Cartes/index.html.twig
{% extends 'template.html.twig' %}

{% block title %}Liste des Cartes
{% endblock %}
{% block PageTitle%}
    Liste totale des Cartes
{% endblock %}
{% block body %}
<div class="row">
    {% for carte in cartes %}
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{carte.name}}</h5>
                <img src="{{ asset('assets/cartes_postales/') ~ carte.imagefront}}" alt="" width="250" height="200">
                <p class="card-text">Prix: {{carte.prix}} DT</p>
                <p class="card-text">Pays: {{carte.pays}}</p>
                <h6 class="card-subtitle mb-2 text-body-secondary">Stock: {{carte.quantiteStock}}</h6>
                <a href="{{path('cards.detail',{id: carte.id})}} " class="btn btn-light">
                    Acheter
                </a>
                {% if is_granted("ROLE_ADMIN") %}
                <a href="{{path('cards.edit',{id: carte.id})}}" class="card-link">
                    <i class="fa-regular fa-pen-to-square"></i>
                </a>
                    <a href="{{path('cards.delete',{id: carte.id})}}" class="card-link">
                        <i class="fa-solid fa-trash"></i>
                    </a>
                    {% endif%}
            </div>
        </div>
    {% endfor %}
</div>
{% if isPaginated is defined and isPaginated%}
    <div class="row">
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                <li class="page-item {% if page==1 %}disabled {% endif %}">
                    <a class="page-link" href="{{ path('cards.paginate', {page:page-1, nbre:nbre} ) }}">Previous</a>
                </li>
                {% for i in range(1,nbrePage) %}
                    <li class="page-item {% if i == page %}active{% endif %}">
                        <a class="page-link" href="{{ path('cards.paginate', {page:i, nbre:nbre} ) }}">{{i}}</a>
                    </li>
                {% endfor %}
                <li class="page-item {% if page==nbrePage %}disabled {% endif %}">
                    <a class="page-link" href="{{ path('cards.paginate', {page:page+1, nbre:nbre} ) }}">Next</a>
                </li>
            </ul>
        </nav>
    </div>
{% endif %}
{% endblock %}